language: node_js
node_js:
- 12
branches:
branches:
  only:
  - develop
deploy:
  provider: heroku
  app: backend-siterotaract2020
  on:
    branch: develop
  api_key:
    secure: MjQlQnNMeCApxNc7Apgeg4bPvj8Q8QGvNcuvNtGjnZ/DCz2ebu5vG5PfBpTzxIv8wzMOGFEni2zSEomkT9HEsiNqT0sAWcV+CzHw0qWyf9qG+st+Jr/deDZyFLPKrOYxwgnlWJmAUuWCFn+3g8/jfB7hezx+InAI9/WlJPCom1zy7e8hAnsJa35QJSC8XFvo4TsH7YgI9vj4YESd1W5ruaB7nHcQVJIUExnLVT+3uiyTF31n23fRIhiY4/INwVoo7QEXn+SNJ/iMaerq1R0zZX5whVXY9i7bzqSY1uYJw+26EdoTwVi/7DW5JJhIJrG8B5W3CV8Hfmi+TiZhforb6quVPQUgvmHunaO+qvFMVIsdAkFBjiMaYa5cNy5ov5im7A8+u+m8gPMuKGztHpxW3arU4YMpqmyoXhRj+T/Eu2VJkMLJ/m42+DhPUowjlSVAI2heyUMjh1uRxj+LrYdYTcEcvlaCFSzEBGTdQRzA10BDV2ymcmL8OpPC1n5ixOayF86o54FFPymqOPV1N15QqSkmgx+6BtJ6gj23XZJnU/PwXBmz/8JGGa8I+s2DBbSl+59keVtFO1hGjBmg6C09KZIu4OXRK/OGcbPL9LfZqTOrExFju0FRP3dJud7toTuCZU23q0V13U00RgORvzCWfdBDBYA64aZDxz5s+efh0O0=